### ISSUE TITLE
Enable users to create and preview their own musical piece

### ISSUE THREAD

**Issue by Puttaranun** [LeroyBG/garticband#1]
## Epic
As users, they want to have a personal space where they can create their own musical piece privately, with the ability to listen to it before sharing or submitting. Users want to have the flexibility to select from a set of instruments to enrich their compositions and expand their creative possibilities. This feature should empower them to experiment with different sounds, and perfect their music in a secure environment, ensuring they have full control before making it public.

## User Stories
- [ ] Users can create a private space for creating musical piece
- [ ] Users can select a set of instruments
- [ ] Users can listen to previous player's piece before composing in their round
- [ ] Users can submit their final music piece

**Comment by nykang17** [comment]
[Link to tasks](https://docs.google.com/spreadsheets/d/1VHGZSvnrM8GlIvgb0Clei95KGKR_BivVOCOocpW_y1U/edit?usp=sharing)
