### ISSUE TITLE
Users can enjoy the multiplayer music composition game with genre-based challenge

### ISSUE THREAD

**Issue by Puttaranun** [LeroyBG/garticband#2]
## Epic
As users, they want to join a multiplayer game in a shared lobby where they can collaborate with others in a unique musical experience. Before composing, they will be assigned a specific music genre to guide their creation. Once all players have completed their individual compositions, the game will sequentially combine all the pieces into musical composition. 

## User Stories
- [ ] Create a shared lobby for multiplayer collaboration
- [ ] Assign a music genre prompt to players
- [ ] Create sequential composition workflow, and review of the final composition
- [ ] Users can start and join the game

**Comment by nykang17** [comment]
[Link to tasks](https://docs.google.com/spreadsheets/d/1VHGZSvnrM8GlIvgb0Clei95KGKR_BivVOCOocpW_y1U/edit?usp=sharing)
